

# Basic
name:               "Gogo Elebiduna"
title:              "Gogo Elebiduna at the University of the Basque Country"
description:        "this is a page for Gogo Elebiduna lab, we are ..."


# URL
url:                http://abazvpo.github.io/lab2
baseurl:            http://abazvpo.github.io/lab2
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           "/lab2/"
  - name:           "about"
    href:           "/lab2/about"
  - name:           "publications"
    href:           "/lab2/publication"
  - name:           "people"
    href:           "/lab2/people"
  - name:           "resources"
    href:           "/lab2/resources"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
